export const books = [
  {
    id: "1",
    title: "Atomic Habits",
    author: "James Clear",
    publishDate: "2018-10-16",
    pages: 320,
    cover_image: "https://m.media-amazon.com/images/I/91bYsX41DVL._AC_UF1000,1000_QL80_.jpg",
    description: "A practical guide on how to build good habits and break bad ones.",
    category: "Self-Help",
    rating: 4.8
  },
  {
    id: "2",
    title: "Dune",
    author: "Frank Herbert",
    publishDate: "1965-08-01",
    pages: 412,
    cover_image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1555447414i/44767458.jpg",
    description: "A Sci-Fi epic about a desert planet, political intrigue, and the struggle for control over a powerful spice.",
    category: "Sci-Fi",
    rating: 4.7
  },
  {
    id: "3",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    publishDate: "1937-09-21",
    pages: 310,
    cover_image: "https://m.media-amazon.com/images/I/91b0C2YNSrL.jpg",
    description: "A fantasy adventure following Bilbo Baggins' journey to reclaim treasure guarded by a dragon.",
    category: "Fantasy",
    rating: 4.8
  },
  {
    id: "4",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    publishDate: "2011-06-04",
    pages: 443,
    cover_image: "https://m.media-amazon.com/images/I/713jIoMO3UL._AC_UF1000,1000_QL80_.jpg",
    description: "A history of humankind from the Stone Age to the modern era.",
    category: "History",
    rating: 4.9
  },
  {
    id: "5",
    title: "The Wright Brothers",
    author: "David McCullough",
    publishDate: "2015-05-05",
    pages: 336,
    cover_image: "https://m.media-amazon.com/images/I/81pFoS4c1IL.jpg",
    description: "The incredible true story of the inventors of the airplane.",
    category: "History",
    rating: 4.8
  },
  {
    id: "6",
    title: "The Martian",
    author: "Andy Weir",
    publishDate: "2011-09-27",
    pages: 369,
    cover_image: "https://wallpapers.com/images/featured/the-martian-u9lthj1y367lwlxv.jpg",
    description: "A gripping Sci-Fi survival story of an astronaut stranded on Mars.",
    category: "Sci-Fi",
    rating: 4.8
  },
  {
    id: "7",
    title: "The Alchemist",
    author: "Paulo Coelho",
    publishDate: "1988-04-15",
    pages: 197,
    cover_image: "https://m.media-amazon.com/images/I/71aFt4+OTOL._AC_UF1000,1000_QL80_.jpg",
    description: "A philosophical novel about following one's dreams.",
    category: "Fiction",
    rating: 4.7
  },
  {
    id: "8",
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    publishDate: "1997-06-26",
    pages: 309,
    cover_image: "https://m.media-amazon.com/images/I/81iqZ2HHD-L.jpg",
    description: "The beginning of the magical journey of a young wizard, Harry Potter.",
    category: "Fantasy",
    rating: 4.9
  },
  {
    id: "9",
    title: "1984",
    author: "George Orwell",
    publishDate: "1949-06-08",
    pages: 328,
    cover_image: "https://mir-s3-cdn-cf.behance.net/project_modules/1400/b468d093312907.5e6139cf2ab03.png",
    description: "A dystopian novel about a totalitarian government and thought control.",
    category: "Dystopian",
    rating: 4.8
  },
  {
    id: "10",
    title: "The Da Vinci Code",
    author: "Dan Brown",
    publishDate: "2003-03-18",
    pages: 489,
    cover_image: "https://bookishloom.wordpress.com/wp-content/uploads/2020/04/513wb5gwt9l.jpg?w=343",
    description: "A thrilling mystery involving secret societies, cryptic messages, and a race against time.",
    category: "Mystery",
    rating: 4.6
  },
  {
    id: "11",
    title: "Educated",
    author: "Tara Westover",
    publishDate: "2018-02-20",
    pages: 352,
    cover_image: "https://m.media-amazon.com/images/I/81WojUxbbFL.jpg",
    description: "A memoir about a woman who grows up in a strict and abusive household but earns a PhD from Cambridge University.",
    category: "Non-Fiction",
    rating: 4.7
  },
  {
    id: "12",
    title: "Gone Girl",
    author: "Gillian Flynn",
    publishDate: "2012-05-24",
    pages: 432,
    cover_image: "https://images2.alphacoders.com/111/1115019.jpg",
    description: "A psychological thriller about a marriage gone terribly wrong.",
    category: "Mystery",
    rating: 4.5
  },
  {
    id: "13",
    title: "The Expanse: Leviathan Wakes",
    author: "James S.A. Corey",
    publishDate: "2011-06-02",
    pages: 561,
    cover_image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRo4CBeXtgMOBlwgvtpnrYDt-KCDqJhtdSuSdOEHGHUqZkggt4avZdAaOhG_5RxsIhG2bu-FhjGqqfyDU7aqtM_j0Ho7OlwtUs2Yj9_OXGn&usqp=CAE",
    description: "A thrilling space opera that kicks off 'The Expanse' series.",
    category: "Sci-Fi",
    rating: 4.7
  },
  {
    id: "14",
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    publishDate: "2007-03-27",
    pages: 662,
    cover_image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1704917687i/186074.jpg",
    description: "The first book in 'The Kingkiller Chronicle,' a gripping fantasy saga.",
    category: "Fantasy",
    rating: 4.8
  },
  {
    id: "15",
    title: "The Way of Kings",
    author: "Brandon Sanderson",
    publishDate: "2010-08-31",
    pages: 1007,
    cover_image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1659905828i/7235533.jpg",
    description: "The first book in 'The Stormlight Archive,' an epic fantasy series.",
    category: "Fantasy",
    rating: 4.9
  },
  {
    id: "16",
    title: "Sherlock Holmes: The Complete Novels and Stories",
    author: "Arthur Conan Doyle",
    publishDate: "1887-10-14",
    pages: 1800,
    cover_image: "https://m.media-amazon.com/images/I/71NI+fGk58L._AC_UF1000,1000_QL80_.jpg",
    description: "A collection of classic mystery detective stories featuring Sherlock Holmes.",
    category: "Mystery",
    rating: 4.9
  },
  {
    id: "17",
    title: "Brave New World",
    author: "Aldous Huxley",
    publishDate: "1932-01-01",
    pages: 311,
    cover_image: "https://images.justwatch.com/poster/317700789/s718/brave-new-world.jpg",
    description: "A dystopian novel exploring the consequences of a technologically advanced society.",
    category: "Dystopian",
    rating: 4.7
  },
  {
    id: "18",
    title: "Foundation",
    author: "Isaac Asimov",
    publishDate: "1951-05-01",
    pages: 296,
    cover_image: "https://i.pinimg.com/736x/51/74/38/517438780ab6f2ad55b4ee48ce844aae.jpg",
    description: "A Sci-Fi classic about the rise and fall of a galactic empire.",
    category: "Sci-Fi",
    rating: 4.8
  }
];
